version: 2

sources:
  - name: main
    database: ae_exam_db
    schema: main
    description: "Main source tables for the food delivery analytics project."
    tables:
      - name: customers_master
        description: "Contains basic information about all customers who have used the food delivery service."

      - name: drivers_master
        description: "Lists all delivery drivers in the system along with their background and service zones."

      - name: restaurants_master
        description: "Includes information about restaurants participating in the platform."

      - name: campaign_master
        description: "Details marketing campaigns that were launched throughout the year."

      - name: order_transactions
        description: "Captures all food delivery orders placed throughout the year, including order time, delivery, and final status."

      - name: support_tickets
        description: "Records customer support requests or complaints related to orders, drivers, or restaurants."

      - name: support_ticket_status_logs
        description: "Tracks the status changes of each support ticket over time."

      - name: campaign_interactions
        description: "Logs customer interactions with marketing campaigns, such as impressions, clicks, and conversions."

      - name: order_log_incentive_sessions_order_status_logs
        description: "Logs the step-by-step status updates for each order from creation to delivery or cancellation."

      - name: order_log_incentive_sessions_driver_incentive_logs
        description: "Stores information about driver bonuses or incentives, including performance targets and qualification status."

      - name: order_log_incentive_sessions_customer_app_sessions
        description: "Tracks customer activity when using the mobile application, including session duration and device used."